CREATE TABLE rovlog(
    id bigint not null primary key autoincrement,
    volts decimal(5.3) not null default 0.0,
    amps decimal(5.3) not null default 0.0,
    motor_l integer not null default 0,
    motor_r integer not null default 0,
    motor_v integer not null default 0,
    temp_i decimal(5.2) not null default 0.0,
    temp_o decimal(5.2) not null default 0.0,
    accel_x decimal(5.2) not null default 0.0,
    accel_y decimal(5.2) not null default 0.0,
    accel_z decimal(5.2) not null default 0.0,
    gyro_x decimal(5.2) not null default 0.0,
    gyro_y decimal(5.2) not null default 0.0,
    gyro_z decimal(5.2) not null default 0.0,
    mag_x decimal(5.2) not null default 0.0,
    mag_y decimal(5.2) not null default 0.0,
    mag_z decimal(5.2) not null default 0.0,
    heading decimal(5.2) not null default 0.0,
    light varchar(50) not null default 'off',
    pressure integer not null default 0,
    moisture integer not null default 0,
    alarm varchar(50) not null default 'false',
    alarm_data integer not null default 0
);